### ISSUE TITLE
Is possible to implement it with gradle?

### ISSUE THREAD

**Issue by d4annn** [gaeqs/JavaYoutubeDownloader#8]

**Comment by gaeqs** [comment]
Yes, you can use Maven packages in Gradle. An implementation using Groovy should look like this:

```
implementation 'io.github.gaeqs:JavaYoutubeDownloader:1.2.3'
```

**Comment by d4annn** [comment]
That worked, but when im trying to use it i get `Unable to decrypt signature!` and `java.io.FileNotFoundException: https://www.youtube.com/get_video_info?video_id=dQw4w9WgXcQ` im providing the hole url, am i doing it right? or i need to provide the video id. This is at the first line `JavaYoutubeDowloader.decodeOrNull()`

**Comment by gaeqs** [comment]
Are you trying to download it ussing the embedded system? The embedded system only works on very old videos.

Try using this:
```java
	YoutubeVideo video = JavaYoutubeDownloader.decode("https://www.youtube.com/watch?v=kJQP7kiw5Fk",
				MultipleDecoderMethod.AND, "html");
```

**Comment by d4annn** [comment]
Im getting the same error


```io.github.gaeqs.javayoutubedownloader.exception.DownloadException: Unable to decrypt signature!
	at io.github.gaeqs.javayoutubedownloader.decrypt.HTML5SignatureDecrypt.decrypt(HTML5SignatureDecrypt.java:119)
	at io.github.gaeqs.javayoutubedownloader.stream.EncodedStream.decodeComplex(EncodedStream.java:153)
	at io.github.gaeqs.javayoutubedownloader.stream.EncodedStream.decode(EncodedStream.java:124)
	at io.github.gaeqs.javayoutubedownloader.decoder.HTMLDecoder.lambda$extractVideo$2(HTMLDecoder.java:80)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at io.github.gaeqs.javayoutubedownloader.decoder.HTMLDecoder.extractVideo(HTMLDecoder.java:80)
	at io.github.gaeqs.javayoutubedownloader.JavaYoutubeDownloader.decode(JavaYoutubeDownloader.java:137)
	at io.github.gaeqs.javayoutubedownloader.JavaYoutubeDownloader.decode(JavaYoutubeDownloader.java:98)
	at getta.gettaroo.features.YoutubeDowloader.download(YoutubeDowloader.java:56)
	at getta.gettaroo.features.YoutubeDowloader.main(YoutubeDowloader.java:51)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "engine" is null
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "engine" is null

	at io.github.gaeqs.javayoutubedownloader.decrypt.HTML5SignatureDecrypt.getScript(HTML5SignatureDecrypt.java:50)
	at io.github.gaeqs.javayoutubedownloader.decrypt.HTML5SignatureDecrypt.decrypt(HTML5SignatureDecrypt.java:116)
	... 9 more
Exception in thread "main" java.lang.IllegalStateException: Couldn't get any video instance
	at io.github.gaeqs.javayoutubedownloader.JavaYoutubeDownloader.decode(JavaYoutubeDownloader.java:149)
	at io.github.gaeqs.javayoutubedownloader.JavaYoutubeDownloader.decode(JavaYoutubeDownloader.java:98)
	at getta.gettaroo.features.YoutubeDowloader.download(YoutubeDowloader.java:56)
	at getta.gettaroo.features.YoutubeDowloader.main(YoutubeDowloader.java:51)
	```

**Comment by gaeqs** [comment]
That's because you're using Java 15 or later. 
You must include a JavaScript engine as a dependency in your project.
[// https://mvnrepository.com/artifact/org.openjdk.nashorn/nashorn-core
implementation("org.openjdk.nashorn:nashorn-core:15.4")
](https://mvnrepository.com/artifact/org.openjdk.nashorn/nashorn-core/15.4)
